

--  what is SQL procedure?
--  A SQL procedure is a stored program that can be executed in the database. 
--  It is a set of SQL statements that perform a specific task, such as retrieving data, updating records, or performing calculations. 
--  Procedures can accept parameters, execute complex logic, and return results. 
--  !!!!!!!!!! They are used to encapsulate business logic and improve code reusability and maintainability.  !!!!!!!!!!!!!!!!!!!!!
--  Procedures are typically created using the CREATE PROCEDURE statement and can be executed using the EXECUTE or CALL statement.
--  Procedures can be written in SQL or PL/SQL, which is Oracle's procedural extension to SQL.

--  waht is PL/SQL procedure?
--  PL/SQL procedure is a block of code that can be executed in the Oracle database
--  It is a set of SQL statements and PL/SQL code that can perform complex operations, such as data manipulation, control flow, and exception handling.
--  PL/SQL procedures can accept parameters, execute complex logic, and return results.

-- is PL/SQL only for Oracle?
--  PL/SQL is Oracle's procedural extension to SQL, so it is primarily used in Oracle databases.
--  However, other database systems may have similar procedural extensions, such as T-SQL in Microsoft SQL Server or PL/pgSQL in PostgreSQL.


--  pros and cons of using PL/SQL procedures in enterprise environments:
--  Pros:
--  1. Performance: PL/SQL procedures can improve performance by reducing network traffic and  
--     allowing for batch processing of data.
--  2. Code Reusability: Procedures can be reused across multiple applications, reducing
--     development time and effort.
--  3. Security: Procedures can encapsulate business logic and restrict direct access to the
--     underlying data, enhancing security.
--  4. Maintainability: Procedures can be easily modified and maintained, allowing for easier
--     updates and changes to business logic.
--  5. Exception Handling: PL/SQL provides robust exception handling mechanisms, allowing for
--     better error management and recovery.
--  Cons:
--  1. Complexity: PL/SQL procedures can become complex, making them harder to understand and maintain.
--  2. Debugging: Debugging PL/SQL procedures can be more challenging compared to other programming languages.
--  3. Vendor Lock-in: PL/SQL is specific to Oracle databases, which can lead to vendor lock-in and limit portability to other database systems.
--  4. Performance Overhead: While PL/SQL can improve performance, poorly designed procedures can lead to performance issues.
--  5. Learning Curve: Developers may need to invest time in learning PL/SQL    
--     if they are not already familiar with it, which can slow down development initially. 
-- 6. Version Compatibility: Different versions of Oracle may have variations in PL/SQL features,
--     which can lead to compatibility issues when upgrading or migrating applications. 
-- 7. Resource Consumption: PL/SQL procedures can consume database resources, such as memory and CPU,
--     especially if they are not optimized properly, leading to potential performance degradation. 
-- 8. Limited Portability: PL/SQL procedures are not easily portable to other database systems,
--     which can make it difficult to migrate applications to different platforms or databases.
-- 9. Dependency Management: PL/SQL procedures may have dependencies on other database objects,
--     such as tables or views, which can complicate deployment and version control.
-- 10. Scalability: In high-transaction environments, PL/SQL procedures may face scalability challenges,
--     especially if they are not designed to handle concurrent access efficiently.
-- 11. Maintenance Overhead: As the number of procedures grows, managing and maintaining them can become cumbersome,
--     requiring proper documentation and version control practices to ensure consistency and reliability.
-- 12. Limited Debugging Tools: While Oracle provides some debugging tools for PL/SQL,
--     they may not be as robust or user-friendly as those available for other programming languages,
--     making it harder to troubleshoot issues effectively.
-- 13. Security Risks: If not properly secured, PL/SQL procedures can expose sensitive data or allow unauthorized access,
--     leading to potential security vulnerabilities in the application.
-- 14. Testing Challenges: Testing PL/SQL procedures can be more complex compared to other programming languages,
--     as it often requires setting up specific database environments and data conditions to ensure accurate results.
-- 15. Limited Language Features: PL/SQL may lack some advanced programming features found in other languages,
--     which can limit the complexity of the logic that can be implemented within procedures.
-- 16. Version Control: Managing changes to PL/SQL procedures can be challenging,
--     especially in collaborative environments where multiple developers are working on the same codebase,
--     requiring proper version control practices to avoid conflicts and ensure consistency.
-- 17. Dependency on Database: PL/SQL procedures are tightly coupled with the Oracle database,
--     which can limit flexibility in terms of application architecture and design,
--     as they are not easily portable to other database systems or environments.
-- 18. Resource Contention: In high-concurrency environments, PL/SQL procedures may face resource contention issues,
--     leading to performance bottlenecks and potential deadlocks if not designed to handle concurrent access efficiently.
-- 19. Limited Support for Object-Oriented Programming: PL/SQL has limited support for object-oriented programming concepts,
--     which can make it challenging to implement complex data structures or design patterns within procedures,
--     potentially leading to less maintainable code.
-- 20. Lack of Standardization: PL/SQL is specific to Oracle databases, which can lead to a lack of standardization
--     across different database systems, making it harder to find developers with expertise in PL/SQL
--     and limiting the ability to share code or best practices across different platforms.
-- 21. Limited Community Support: Compared to more widely used programming languages,
--     the PL/SQL community may be smaller, leading to fewer resources, libraries, and frameworks available for developers,
--     which can slow down development and limit access to community-driven solutions.